CREATE TABLE Assignament (
  RADICACION INT PRIMARY KEY,
  TIPOQUEJA VARCHAR(50),
  DELEGADO VARCHAR(50),
  ESTADO VARCHAR(50),
  RESPONSABLE VARCHAR(50),
  AREA_RESPONSABLE VARCHAR(50),
  TIPO_PROCESO VARCHAR(50),
  ORIGEN VARCHAR(50),
  NOMBREAFECTADO VARCHAR(50),
  FECHA_RADICACION DATE,
  HORA_RADICACION TIME,
  FECHA_LIMITE DATE,
  NOMBRE_RECLAMANTE VARCHAR(50),
  ID_RECLAMANTE INT,
  EMPRESA_RECLAMANTE VARCHAR(50),
  PRODUCTO VARCHAR(50),
  QUEJ_RADICADOR VARCHAR(50),
  IPS VARCHAR(50),
  DONDE_SUCEDIO VARCHAR(50),
  DOC_AFECTADO VARCHAR(50),
  TEL_OFIC_RECLAMANTE VARCHAR(50),
  TEL_CASA_RECLAMANTE VARCHAR(50),
  DIR_CORRESP_RECLAMANTE VARCHAR(50),
  RESUMEN_QUEJA VARCHAR(500),
  QUEJ_MAX_DIAS INT
  FECHA_RESUELTO VARCHAR (10)
  RESUELTO VARCHAR (2)
  OBSERVACIONES VARCHAR (100)
  CORREO VARCHAR (100)
  MUNICIPI0 VARCHAR (50)
  DEPARTAMENTO VARCHAR (50)
);
